### ISSUE TITLE
iOS availability

### ISSUE THREAD

**Issue by sandoche** [jayson-temporas/nativescript-temp-sms#2]
Hello,

I am using it for Android it works good!
Do you know when this will be available for iOS?

**Comment by sandoche** [comment]
Also I just saw this:
https://stackoverflow.com/questions/9570642/send-sms-programmatically-without-the-sms-composer-window

**Comment by jayson-temporas** [comment]
I already abandoned this project. Please try to use other plugins.

**Comment by sandoche** [comment]
It worked good on Android, but Google Play decided to limitate the SMS permission, So I went to another plugin that let the user press the button. And it also works for iOS. You can have a look here if you want: https://textblast.learn.uno

Thanks for the answer.
